%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%       func_InitializeStructures.m
%           made by J. Turnquist, GI UAF
%
%       ver.1.0: Jun-24-2008: Initialize structures to be used throught 
%
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [ InputParam, RadarParam, GenParam ] = func_InitializeStructures

%------
% set global parameters
%------
% global_HaarpMUIRAnalysis

%% Initilize empty Input Paramter Structure
%%
 InputParam = struct( 'Directory4MUIRData',[]       ...
                    , 'SelectedDateChar',[]         ...
                    , 'ExpNumberChar', []           ...
                    , 'SaveFigExt', []              ...
                    , 'PulseType',[]                ...
                    , 'SaveDirectory',[] );

%% Initialize empty Radar Parameter Structrue
%%
RadarParam = struct( 'SamplingRate',[]              ...
                   , 'PulseLength',[]               ...
                   , 'IPP',[]                       ...
                   , 'StartTime4Tx',[]              ...
                   , 'StartTime4Rx',[]              ...
                   , 'DefaultIntTime',[]            ...
                   , 'TransmitFreq',[]              ...
                   , 'PulseSequence',[]             ...
                   , 'IntegratedTimeLength',[]      ...
                   , 'ReceivingCenterFrequency',[]  ...
                   , 'ReceivingBandWidth',[]        ...
                   , 'BeamDir',[]                   ...
                   , 'PhaseCoding',[]);
                
%% Initialize empty General Parameter Structure
%%s
GenParam = struct( 'SelectedDirChar',[]             ...
                 , 'FileNameArr',[]                 ...
                 , 'FileNameNum',[]                 ...
                 , 'SelectedFileNames',[]           ...
                 , 'SelectedFileNumbers',[]         ...
                 , 'CalROIFlag', []                 ...
                 , 'ROITime',[]                   	...
                 , 'IntegratedTimeLength',[]        ...
                 , 'UpperHeight',[]                 ...
                 , 'LowerHeight',[]);
              

              